[package]
name = "electrolite"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "electrolite-server"
path = "server/main.rs"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled", "hooks"] }
serde_json = "1"
tiny_http = "0.12"
getrandom = "0.2"

[dev-dependencies]
tempfile = "3"
